development:
    twitter:
        username: 'iamcutler'
        consumer_key: 'oWk4AEmPovmNix65sIOXzSunl'
        consumer_secret: 'Fjv8ydXAvTZuknGWQH91HawsqVSGaHTTh9TLxYU71HbbquNTkE'
        oauth_token: '45640539-dQyZ5saSjFm0Rhnzc2nGTavWYzIAkCIxqXcS49dp3'
        oauth_token_secret: 'jbp4d8rvJwu2W2HWi3BQz89dtxlbUfMQHDP14aM78fggo'

test:
    twitter:
        username: 'iamcutler'
        consumer_key: 'oWk4AEmPovmNix65sIOXzSunl'
        consumer_secret: 'Fjv8ydXAvTZuknGWQH91HawsqVSGaHTTh9TLxYU71HbbquNTkE'
        oauth_token: '45640539-dQyZ5saSjFm0Rhnzc2nGTavWYzIAkCIxqXcS49dp3'
        oauth_token_secret: 'jbp4d8rvJwu2W2HWi3BQz89dtxlbUfMQHDP14aM78fggo'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    twitter:
        username: <%= ENV["TWITTER_FEED_NAME"] %>
        consumer_key: <%= ENV["TWITTER_COMSUMER_KEY"] %>
        consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
        oauth_token: <%= ENV["TWITTER_OAUTH_TOKEN"] %>
        oauth_token_secret: <%= ENV["TWITTER_OAUTH_SECRET"] %>
